packages:
  device_base: !include templates/device_base.yaml

wifi: !include templates/wifi_iot.yaml

substitutions:
  devicename: garagerelays
  friendly_name: Garage Relay Board
  device_description: The finest Chineasuem

esphome:
  name: ${devicename}
  comment: ${device_description}

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: debug

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO25
      mode: INPUT_PULLUP
    name: ${friendly_name} Relay 1 Switch
    on_state:
      - switch.toggle: relay1
  - platform: gpio
    pin:
      number: GPIO26
      mode: INPUT_PULLUP
    name: ${friendly_name} Relay 2 Switch
    on_state:
      - switch.toggle: relay2
#  - platform: gpio
#    pin:
#      number: GPIO1
#      mode: INPUT_PULLUP
#    name: ${friendly_name} Relay 3 Switch
#    on_state:
#      - switch.toggle: relay3
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
    name: ${friendly_name} Relay 4 Switch
    on_state:
      - switch.toggle: relay4

switch:
  - platform: gpio
    name: ${friendly_name} Relay 4
    pin: GPIO19
    id: relay4
  - platform: gpio
    name: ${friendly_name} Relay 3
    pin: GPIO18
    id: relay3
  - platform: gpio
    name: ${friendly_name} Relay 2
    pin: GPIO17
    id: relay2
  - platform: gpio
    name: ${friendly_name} Relay 1
    pin: GPIO16
    id: relay1