packages:
  device_base: !include templates/device_base.yaml
  esphome: !include templates/wemos1mini/esphome.yaml
  substitutions: !include templates/wemos1mini/substitutions.yaml

wifi: !include templates/wifi_iot.yaml

substitutions:
  devicename: housealarmsw
  friendly_name: House Alarm Switch

switch:
  - platform: gpio
    name: ${friendly_name} Relay
    pin: D6
    inverted: yes
    restore_mode: ALWAYS_OFF
    id: relay
  - platform: template
    name: ${friendly_name} Relay Moment Button
    icon: "mdi:gesture-tap-button"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay