packages:
  device_base: !include templates/device_base.yaml
  switch: !include templates/sonoff_r2/switch.yaml
  binary_sensor: !include templates/sonoff_r2/binary_sensor.yaml
  status_led: !include templates/sonoff_r2/status_led.yaml
  esphome: !include templates/sonoff_r2/esphome.yaml
  substitutions: !include templates/sonoff_r2/substitutions.yaml

wifi: !include templates/wifi_iot.yaml

substitutions:
  devicename: outsiderearlights
  friendly_name: Outside Rear Lights

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    name: ${friendly_name} Manual Switch
    on_state:
      - switch.toggle: relay