packages:
  device_base: !include templates/device_base.yaml
  esphome: !include templates/wemos1mini/esphome.yaml
  substitutions: !include templates/wemos1mini/substitutions.yaml

wifi: !include templates/wifi_iot.yaml

substitutions:
  devicename: smartmeters
  friendly_name: Smart Meter LED sensor

i2c:
  - id: bus_a
    sda: D2
    scl: D1

sensor:
  - platform: bh1750
    i2c_id: bus_a
    name: Outside Illuminance
    address: 0x23
    update_interval: 15s
    id: light1
  - platform: pulse_meter
    pin: D3
    name: "House Electricity Meter kw"
    internal_filter: 35ms
    unit_of_measurement: 'kW'
    filters:
      - multiply: 0.015
    total:
      name: "House Electricity Meter Total"
      device_class: energy
      unit_of_measurement: 'kWh'
      accuracy_decimals: 2
      filters:
        - multiply: 0.00025