packages:
  device_base: !include templates/device_base.yaml
  esphome: !include templates/wemos1mini/esphome.yaml
  substitutions: !include templates/wemos1mini/substitutions.yaml

wifi: !include templates/wifi_iot.yaml

substitutions:
  devicename: utilityroomlightsensor
  friendly_name: Utility Room Outside Light SW

sensor:
  - platform: adc
    pin: A0
    name: ${friendly_name} Switch
    update_interval: 500ms
    filters:
      - multiply: 3.3
      - delta: 1.5