api:

binary_sensor:
  - platform: status
    name: ${friendly_name} Status

captive_portal:

esphome:
  name: ${devicename}
  comment: ${device_description}

http_request:
  useragent: esphome/$devicename
  timeout: 2s

logger:
  level: WARN
  baud_rate: 0

ota:
  safe_mode: true
  password: !secret ota_password

sensor:
  - platform: uptime
    name: ${friendly_name} Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes
  - platform: wifi_signal
    name: ${friendly_name} Wifi Signal
    update_interval: 60s

switch:
  - platform: restart
    name: ${friendly_name} Restart

web_server:
  port: 80
  version: 2
  include_internal: true

wifi:
  ap:
    ssid: "ESPDev"
    password: "HelpHelp"